name: Build Docs

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme

    - name: Build Documentation
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')
        OUTPUT_FOLDER="docs/_build/${BRANCH_NAME}"

        sphinx-quickstart -q -p docs source
        sphinx-build -b html source "${OUTPUT_FOLDER}"
        touch "${OUTPUT_FOLDER}/.nojekyll"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/${BRANCH_NAME}